2022-12-08 11:29:10,636 ERROR app Thread-11 : Exception on /apiv1/file [GET]
Traceback (most recent call last):
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\app.py", line 55, in fileread
    filename = data['file']
FileNotFoundError: [Errno 2] No such file or directory: 'data1.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\app.py", line 61, in fileread
    print(e)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type FileNotFoundError is not JSON serializable
2022-12-08 11:29:10,638 INFO werkzeug Thread-11 : 127.0.0.1 - - [08/Dec/2022 11:29:10] "[35m[1mGET /apiv1/file HTTP/1.1[0m" 500 -
2022-12-08 11:29:53,234 INFO werkzeug MainThread :  * Detected change in 'D:\\Masters degree\\SEM 3\\Datacenter scale Computing\\Project\\Project\\Distributed-Log-Analyzer\\Logger\\app.py', reloading
2022-12-08 11:29:53,267 INFO werkzeug MainThread :  * Restarting with stat
2022-12-08 11:29:54,075 WARNING werkzeug MainThread :  * Debugger is active!
2022-12-08 11:29:54,089 INFO werkzeug MainThread :  * Debugger PIN: 109-160-928
2022-12-08 11:30:02,336 INFO werkzeug MainThread :  * Detected change in 'D:\\Masters degree\\SEM 3\\Datacenter scale Computing\\Project\\Project\\Distributed-Log-Analyzer\\Logger\\app.py', reloading
2022-12-08 11:30:02,374 INFO werkzeug MainThread :  * Restarting with stat
2022-12-08 11:30:02,863 WARNING werkzeug MainThread :  * Debugger is active!
2022-12-08 11:30:02,871 INFO werkzeug MainThread :  * Debugger PIN: 109-160-928
2022-12-08 11:30:05,662 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-08 11:30:05,662 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-08 11:30:05,663 INFO werkzeug MainThread :  * Restarting with stat
2022-12-08 11:30:06,492 WARNING werkzeug MainThread :  * Debugger is active!
2022-12-08 11:30:06,509 INFO werkzeug MainThread :  * Debugger PIN: 109-160-928
2022-12-08 11:30:10,172 ERROR app Thread-12 : Exception on /apiv1/file [GET]
Traceback (most recent call last):
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\app.py", line 55, in fileread
    filename = data['file']
FileNotFoundError: [Errno 2] No such file or directory: 'data1.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\app.py", line 61, in fileread
    print(e)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type FileNotFoundError is not JSON serializable
2022-12-08 11:30:10,175 INFO werkzeug Thread-12 : 127.0.0.1 - - [08/Dec/2022 11:30:10] "[35m[1mGET /apiv1/file HTTP/1.1[0m" 500 -
2022-12-08 13:20:09,156 ERROR app Thread-13 : Exception on /apiv1/file [GET]
Traceback (most recent call last):
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\app.py", line 55, in fileread
    def fileread():
FileNotFoundError: [Errno 2] No such file or directory: 'data1.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\app.py", line 61, in fileread
    data = file.readlines()
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type FileNotFoundError is not JSON serializable
2022-12-08 13:20:09,166 INFO werkzeug Thread-13 : 127.0.0.1 - - [08/Dec/2022 13:20:09] "[35m[1mGET /apiv1/file HTTP/1.1[0m" 500 -
2022-12-08 13:22:35,839 ERROR app Thread-14 : Exception on /apiv1/file [GET]
Traceback (most recent call last):
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\app.py", line 55, in fileread
    def fileread():
FileNotFoundError: [Errno 2] No such file or directory: 'data1.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\app.py", line 61, in fileread
    data = file.readlines()
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Dhrumil\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Masters degree\SEM 3\Datacenter scale Computing\Project\Project\Distributed-Log-Analyzer\Logger\venv\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type FileNotFoundError is not JSON serializable
2022-12-08 13:22:35,843 INFO werkzeug Thread-14 : 127.0.0.1 - - [08/Dec/2022 13:22:35] "[35m[1mGET /apiv1/file HTTP/1.1[0m" 500 -
